
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-08T11:14:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c22fafd4d8fe148f6b2349518188eb0bee5f18f1",
 "version": "0.0.1rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
